[package]
name = "rdp"
version = "0.2.5"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
description = "A Rust implementation of the Ramer–Douglas–Peucker and Visvalingam-Whyatt algorithms"
readme = "README.md"
keywords = ["geo", "Ramer", "Douglas-Peucker", "Visvalingam-Whyatt"]
repository = "https://github.com/urschrei/rdp"
license = "MIT"

[dependencies]
libc = "0.2.14"
geo = "0.3.2"
num = "0.1"

[lib]
name = "rdp"
crate-type = ["rlib", "cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
